plugins {
    id 'net.fabricmc.fabric-loom' version "1.16-SNAPSHOT"
}
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }

    withSourcesJar()
}

version = "0.4.0"
group = "dev.chachy"

dependencies {
    minecraft "com.mojang:minecraft:26.1"
    implementation "net.fabricmc:fabric-loader:0.18.6"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release.set(21)
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.name}" }
    }
}